# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "CV"
  url = "files/cv_ing.pdf"
  weight = 10

[[main]]
    name = "Research"
    url = "#working-papers"
    weight = 20

[[main]]
    name = "Teaching"
    url = "#teaching"
    weight = 40

[[main]]
    name = "Public Goods"
    url = "#posts"
    weight = 50

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

